// <auto-generated />
namespace fantasyF1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sixthmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sixthmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202101101931304_sixth-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
